### ISSUE TITLE
Error With Showcase Library "java.lang.IllegalArgumentException: radius must be > 0"

### ISSUE THREAD

**Issue by Fz-commits** [erkutaras/ShowcaseView#25]
After library integration when i run my app show these errors...!
Can you help me please.

 java.lang.IllegalArgumentException: radius must be > 0
        at android.graphics.RadialGradient.<init>(RadialGradient.java:91)
        at com.erkutaras.showcaseview.ShowcaseView.dispatchDraw(ShowcaseView.kt:159)
        at android.view.View.updateDisplayListIfDirty(View.java:18141)
        at android.view.View.draw(View.java:18928)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)

**Comment by erkutaras** [comment]
I added radius zero check to related function in **v1.3.8**. To solve this error, you can use ShowcaseManager after view inflation. Thanks.
